version: "3.8"

services:
  fastapi:
    build: .
    volumes: 
      - ./recipes_api:/recipes/
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head
             python3 main.py
             python3 ./fixtures/load_fixtures.py"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipes
      - DB_HOST=pgdb
      - DB_PORT=5432

    depends_on:
      - pgdb
      - redis_db

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis_db:
    image: "redis:latest"


volumes:
  pgdata:
