version: "3.8"

services:
  fastapi:
    build: .
    volumes: 
      - ./recipes_api:/recipes/
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head
             pytest -s"
    environment:
      - DB_USER=postgres_test
      - DB_PASSWORD=postgres_test
      - DB_NAME=recipes_test
      - DB_HOST=test_pgdb
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      test_pgdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  test_pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=recipes_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_test -d recipes_test"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "6380:6379"

