version: "3.8"

services:
  fastapi:
    build: .
    volumes: 
      - ./recipes_api:/recipes_api/
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head
             python3 main.py"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipes
      - DB_HOST=pgdb
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      pgdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipes"]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "6380:6379"


volumes:
  pgdata:
