"""Created Recipy author_id and recipy name unique constraint

Revision ID: c7c9f972e622
Revises: d75c3d253e78
Create Date: 2024-10-28 12:29:17.246052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c9f972e622'
down_revision: Union[str, None] = 'd75c3d253e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_author_title', 'atricles', ['author_id', 'title'])
    op.create_unique_constraint('uq_author_name', 'recipes', ['author_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_author_name', 'recipes', type_='unique')
    op.drop_constraint('uq_author_title', 'atricles', type_='unique')
    # ### end Alembic commands ###
