"""Added Article-User one to many relationship, added user.id ForeignKey in Recipy model instead of user.username

Revision ID: d75c3d253e78
Revises: e9b771f68ae6
Create Date: 2024-10-25 16:05:10.024702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75c3d253e78'
down_revision: Union[str, None] = 'e9b771f68ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atricles', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'atricles', 'users', ['author_id'], ['id'])
    op.add_column('recipes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('recipes_author_fkey', 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['author_id'], ['id'])
    op.drop_column('recipes', 'author')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('recipes', sa.Column('author', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key('recipes_author_fkey', 'recipes', 'users', ['author'], ['email'])
    op.drop_column('recipes', 'author_id')
    op.drop_constraint(None, 'atricles', type_='foreignkey')
    op.drop_column('atricles', 'author_id')
    # ### end Alembic commands ###
