"""empty message

Revision ID: e9b771f68ae6
Revises: 6df9a5698e11
Create Date: 2024-10-23 11:40:55.655893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b771f68ae6'
down_revision: Union[str, None] = '6df9a5698e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atricles', sa.Column('image_filename', sa.String(), nullable=False))
    op.drop_column('atricles', 'image_path')
    op.add_column('recipes', sa.Column('image_filename', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('avatar_filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'username')
    op.drop_column('recipes', 'image_filename')
    op.add_column('atricles', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('atricles', 'image_filename')
    # ### end Alembic commands ###
